# Default values for dns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

externalDNS:
  repository: k8s.gcr.io/external-dns/external-dns
  pullPolicy: Always
  tag: v0.10.1

  # Allows to override the name of the objects related to external-dns
  nameOverride: ""

  # If external-dns try to read istio objects without istio installed it will
  # fail with an error "failed to sync cache: timed out waiting for the condition"
  # This flag allows to enable or disable looking for istio's objects
  sourceIstioObjects: false

  extraConfig:
    EXTERNAL_DNS_INTERVAL: 30s
    EXTERNAL_DNS_EVENTS: "1"
  # EXTERNAL_DNS_METRICS_ADDRESS: ":7979"

  # EXTERNAL_DNS_REGISTRY: txt
  # EXTERNAL_DNS_TXT_OWNER_ID: kang

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 256Mi

pdns:
  repository: kangcode/pdns
  pullPolicy: Always
  tag: 1.1-4.2.3

  # Allows to override the name of the objects related to PowerDNS
  nameOverride: ""

  config:
    apiKey: ""

  extraConfig: {}
  # lines in the pdns.conf. These are already harcoded:
  # launch: gsqlite3
  # gsqlite3-database: /data/db
  # webserver: yes
  # webserver-address: 0.0.0.0
  # webserver-port: 80
  # api: yes
  # api-key: ### from config above ###
  # webserver-allow-from: 0.0.0.0/0

  httpService:
    enabled: true
    port: 80
    annotations: {}

  ingress:
    enabled: false

  # TODO: Document? Is it valid empty?
  # className: ""
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   kubernetes.io/tls-acme: "true"
  # hosts:
  #   - host: chart-example.local
  #     paths: []
  # tls: []
  #   - secretName: chart-example-tls
  #     hosts:
  #       - chart-example.local

  udpService:
    enabled: true
    port: 53
    annotations: {}
    # external-dns.alpha.kubernetes.io/hostname: ns1.test.es,ns2.test.es,ns1.test.dev,ns2.test.dev
    # external-dns.alpha.kubernetes.io/ttl: "300"
    # metallb.universe.tf/address-pool: example

  tcpService:
    enabled: true
    port: 53
    annotations: {}
    # metallb.universe.tf/address-pool: example

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 256Mi

  zones: {}
  # test.es: |
  #   $ORIGIN .
  #   test.es   300  IN SOA      ns1.test.es sysadmin.test.es 1 600 600 86400 300
  #   test.es   300  IN NS	      ns1.test.es
  #   test.es   300  IN NS	      ns2.test.es
  #   test.es   300  IN MX	  10  mx.test.es
  # test.dev: |
  #   $ORIGIN .
  #   test.dev   300  IN SOA      ns1.test.dev sysadmin.test.dev 1 600 600 86400 300
  #   test.dev   300  IN NS	      ns1.test.dev
  #   test.dev   300  IN NS	      ns2.test.dev
  #   test.dev   300  IN MX	  10  mx.test.dev


serviceAccount:
  create: true
  annotations: {}
  name: ""

deploymentAnnotations: {}
  # reloader.stakater.com/auto: "true"

podAnnotations: {} # TODO: Prometheus metrics?
